### ISSUE TITLE
Support for pen input

### ISSUE THREAD

**Issue by antonioberetini** [ax-design/reveal-highlight#12]
This was originally implented for pen input on windows devices. Any chance to add support for pen input on mobile and desktop in your implemention?

**Comment by Losses** [comment]
All of us on the team have Surface but unfortunately almost everyone has lost their pens, we have to do something about it
It's embarrassing...

**Comment by Losses** [comment]
It should be solved on 0.2.0?

**Comment by Losses** [comment]
This problem is fixed, thank for your support!
