### ISSUE TITLE
Weird jittering artefacts on the reveal object

### ISSUE THREAD

**Issue by antonioberetini** [ax-design/reveal-highlight#13]
When zoomed, effect elements seem to be jittering, see attached video

https://user-images.githubusercontent.com/65619488/106605139-3064b100-6526-11eb-8cab-26ebbbdaff85.mp4

**Comment by Losses** [comment]
I'll check it, can you provide your environment information?

**Comment by antonioberetini** [comment]
> I'll check it, can you provide your environment information? 

This was reproduced on windows 10 machine and Surface Book 2 in both chrome and chromium edge all latest versions. I'll check if I can reproduce on Android today.

**Comment by Losses** [comment]
> > I'll check it, can you provide your environment information?
> 
> This was reproduced on windows 10 machine and Surface Book 2 in both chrome and chromium edge all latest versions. I'll check if I can reproduce on Android today.

Okay, thank you!

btw, same thing happens on alpha version?

**Comment by Losses** [comment]
This problem should be solved on 0.2.0?

**Comment by Losses** [comment]
This problem is fixed, thank for your support!
